### ISSUE TITLE
Script does not show information on OS X

### ISSUE THREAD

**Issue by jrgz** [dylanaraps/fetch.sh#7]
When I run the script, everything is properly formatted, but no information is printed for most items. 

Missing:
- OS information
- Uptime
- Packages
- Window Manager
- CPU
- Memory
- Song (I assume because of the mpc dependency)
- Image (also probably because of missing dependencies)

Color blocks print successfully.

Here's a picture:
http://imgur.com/2i9zujy

Terminal is iTerm2 (script runs the same on the default Terminal app) and I'm running OS X 10.11.2

**Comment by dylanaraps** [comment]
Alright, thanks!

The image dependencies are w3m and imagemagick, you can use the flag ```--images off``` to disable images/padding.

I'll start working on the OS X version and I'll be posting command one liners in here I'd like you to test. 

Thanks

**Comment by dylanaraps** [comment]
This is for OS detection, the echo will be replaced with ```distro="Mac OS X"```. Are you able to tell me if works? (Does the echo part run?)

```sh
[ "$(grep -i "Mac OS X" /usr/bin/sw_vers)" == "Mac OS X" ] && echo "Found OS X"
```

**Comment by jrgz** [comment]
Does not work. Nothing is returned.

http://i.imgur.com/Pq98EYq.png

**Comment by dylanaraps** [comment]
My bad, I misquoted the string. Try this.

```sh
[ "$(grep -i 'Mac OS X' /usr/bin/sw_vers)" == "Mac OS X" ] && echo "Found OS X"
```

**Comment by jrgz** [comment]
Nothing again.
http://i.imgur.com/F99AfLf.png

**Comment by dylanaraps** [comment]
And ```uname```?

**Comment by jrgz** [comment]
`uname` returns `Darwin`, the Unix kernel on which OS X is based (I think?).

For your reference:
http://i.imgur.com/kSkr3Sr.png

**Comment by dylanaraps** [comment]
I can work with the uname output, thanks!

**Comment by dylanaraps** [comment]
What do these output?

```sw_vers -productVersion```

```system_profiler SPSoftwareDataType```

**Comment by jrgz** [comment]
`10.11.2`

and

    Software:

        System Software Overview:

          System Version: OS X 10.11.2 (15C50)
          Kernel Version: Darwin 15.2.0
          Boot Volume: Macintosh HD
          Boot Mode: Normal
          Computer Name: Jorge’s MacBook Pro
          User Name: Jorge Gonzalez (jorge)
          Secure Virtual Memory: Enabled
          System Integrity Protection: Enabled
          Time since boot: 1 day 47 minutes

**Comment by dylanaraps** [comment]
Awesome!

**Comment by dylanaraps** [comment]
What about this command?

```pkgutil --pkgs | wc -l```

**Comment by jrgz** [comment]
853

**Comment by dylanaraps** [comment]
What package manager would you prefer I get package count from? That command above prints your system's packages but screenfetch seems to only support homebrew, ports or pkgsrc.

**Comment by jrgz** [comment]
Getting the count from pkgutil is fine with me.

**Comment by dylanaraps** [comment]
Awesome, what's the output of this?:

```sysctl -n machdep.cpu.brand_string```

**Comment by jrgz** [comment]
`Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz`

**Comment by dylanaraps** [comment]
Ah, it prints the speed too!

Thanks

**Comment by dylanaraps** [comment]
Here's a version to test out:

http://pastie.org/pastes/10663498/text?key=fgw9adr67vpispggamkjza

Everything should work apart from the Window manager, Song and Image. Upload a screenshot this time :)

**Comment by jrgz** [comment]
No go.
http://i.imgur.com/GoP5uCi.png
Did I possibly run it wrong?

**Comment by dylanaraps** [comment]
I've figured out the problem!

I'll quickly fix it and upload another version.

**Comment by dylanaraps** [comment]
Try this one:

http://pastie.org/pastes/10663511/text?key=0ebzukakggv4ll0tpkjpq

**Comment by jrgz** [comment]
http://i.imgur.com/TNCK5Kr.png

I had to stretch the terminal window to get the CPU info in one line.

**Comment by dylanaraps** [comment]
Alright, So:

- Uptime is broken
- Packages has whitespace
- Cpu has an extra "@ GHz" on the end
- Memory is broken

Thanks!

**Comment by dylanaraps** [comment]
The issues above should be gone now!

http://pastie.org/pastes/10663521/text?key=hdkowzse3wama5ffdlga

**Comment by jrgz** [comment]
http://i.imgur.com/yh9mlZ0.png
Uptime still looks broken

**Comment by dylanaraps** [comment]
Damn I'll fix it in a sec. 

So all that's left now is Window manager and Uptime for the info? (Song needs mpd).

**Comment by jrgz** [comment]
Yes that's all.

**Comment by dylanaraps** [comment]
Awesome!

What does this command output?

```sh
uptime | awk -F'( |,|:)+' '{print $6,$7",",$8,"hours,",$9,"minutes."}'
```

**Comment by jrgz** [comment]
`3 12, 2 hours, users minutes.`

**Comment by dylanaraps** [comment]
What's the output of ```uptime``` on it's own?

**Comment by jrgz** [comment]
`22:39  up 1 day,  3:13, 2 users, load averages: 4.11 4.32 2.89`

**Comment by dylanaraps** [comment]
What about this? (I used Arch's uptime as a base above so I'm just going by your latest msg and it'll be trial and error.)

```sh
uptime | awk -F'( |,|:)+' '{print $5",",$6,"hours,",$7,"minutes."}'
```

**Comment by jrgz** [comment]
`day, 3 hours, 20 minutes.`

**Comment by dylanaraps** [comment]
Hm

```sh
uptime | awk -F'( |,|:)+' '{print $3,$4,$5",",$6,"hours,",$7,"minutes."}'
```

**Comment by jrgz** [comment]
`up 1 day, 3 hours, 27 minutes.`

**Comment by dylanaraps** [comment]
Awesome! 

There's one issue with that though, what happens if the day field is less than 1?

**Comment by jrgz** [comment]
I'm not really sure.

**Comment by dylanaraps** [comment]
I'm currently doing a complete rewrite of the script factoring in other operating systems from the start. When I wrote this script I never intended for it to be used on anything other than arch linux. It's pretty messy at the moment.

There's no rush but next time you reboot your mac, run this command from above and tell me the output:

```sh
uptime | awk -F'( |,|:)+' '{print $3,$4,$5",",$6,"hours,",$7,"minutes."}'
```

You've been really helpful today. 

Thanks!

**Comment by jrgz** [comment]
`47 up 1, day hours, 6 minutes.`

No problem

**Comment by dylanaraps** [comment]
What's the output of ```uname -o```?

**Comment by dylanaraps** [comment]
I pushed the rewrite to master, everything but uptime *should* work now. I still haven't come up with a way to get uptime, I'll try and figure it out asap. 

If you're having any issues with the new version let me know!

**Comment by jrgz** [comment]
This is all that prints now:
 ```
fetch.sh: line 761: syntax error near unexpected token `&'
fetch.sh: line 761: `            ;;&'`
```

**Comment by dylanaraps** [comment]
What shell are you using?

**Comment by dylanaraps** [comment]
I just had a look and the error you're getting is because you're on bash 3.x and I'm using a feature from 4.0.

Bash 4.0 came out in **Feb 2009** so I'm not going to add support for bash 3.x seeing as 4.0 is **7 years old**. 

You'll have to update bash or use another shell to get my script working.

**Comment by jrgz** [comment]
I am using Bash 4.3.

http://i.imgur.com/HxAoDZX.png

**Comment by jrgz** [comment]
I was running the script with `sh fetch.sh` (which I thought was the right way to do so), but if I run it with `bash fetch.sh`, it works.

http://i.imgur.com/DahzMLt.png

**Comment by dylanaraps** [comment]
I see, my bad.

- ```sh fetch.sh``` works on my pc, weird.

- You can remove the image errors by running the script with "--images off". This will also align the text to the left of the window.

-  I'm not sure why packages is popping up as "Unknown", I'll take a look. 

- As for uptime, what does this print? ```uptime | awk -F',' '{ print $1 }'```

**Comment by dylanaraps** [comment]
I just pushed a fix for the packages to master. It should work now.

**Comment by jrgz** [comment]
`uptime | awk -F',' '{ print $1 }'` prints `22:44  up 37 mins`.

`sh fetch.sh` no longer works for some reason. Ran this with `bash fetch.sh --images off`. Memory also seems to be broken now.

http://i.imgur.com/nf5xevE.png

**Comment by dylanaraps** [comment]
Oops, 

- ```(standard_in) 1: parse error``` Is related to the memory and I know how to fix it now.

- ```sh fetch.sh``` isn't working now because I'm using the ```;;&`` case terminator which sh doesn't support afaik.

- I can work with that for the uptime. Cool.

**Comment by dylanaraps** [comment]
Memory *should* be fixed now. 

Please test.

**Comment by jrgz** [comment]
Memory is fixed and everything is good now except uptime.

**Comment by dylanaraps** [comment]
I just pushed uptime for OS X as well.

Please test it too!

**Comment by jrgz** [comment]
Looks odd.  Uptime says `  up  1:01`.

**Comment by dylanaraps** [comment]
Oh, weird. 

Try now.

**Comment by jrgz** [comment]
Still the same.

**Comment by jrgz** [comment]
As in, now it's `up 1:07`.

**Comment by dylanaraps** [comment]
This is how screenfetch does it:

```
boot=$(sysctl -n kern.boottime | cut -d "=" -f 2 | cut -d "," -f 1)
now=$(date +%s)
uptime=$(($now-$boot))

echo "$uptime"
```

Does it work on your system?

**Comment by jrgz** [comment]
That only outputs `4062`.

**Comment by dylanaraps** [comment]
How about this? Turns out screenfetch does some math on the variable later on.

```sh
boot=$(sysctl -n kern.boottime | cut -d "=" -f 2 | cut -d "," -f 1)
now=$(date +%s)
uptime=$(($now-$boot))

secs=$((${uptime}%60))
mins=$((${uptime}/60%60))
hours=$((${uptime}/3600%24))
days=$((${uptime}/86400))
uptime="${mins}m"

if [ "${hours}" -ne "0" ]; then
    uptime="${hours}h ${uptime}"
fi
if [ "${days}" -ne "0" ]; then
    uptime="${days}d ${uptime}"
fi

echo "$uptime"
```

**Comment by jrgz** [comment]
`1h 11m`

**Comment by dylanaraps** [comment]
That seems fine to me, are you happy with it or would you prefer we try and imitate ```uptime -p```?

```uptime -p``` prints:

```
up 6 hours, 47 minutes
```

**Comment by dylanaraps** [comment]
Also what's the output of ```sysctl -n kern.boottime``` ?

**Comment by jrgz** [comment]
I'm more than happy with the former :)

`{ sec = 1451876824, usec = 0 } Sun Jan  3 22:07:04 2016`

**Comment by dylanaraps** [comment]
Now that we have a base I'll work on getting the former working. I shouldn't be too long!

**Comment by dylanaraps** [comment]
I just pushed it to master. Please try it out!

**Comment by jrgz** [comment]
Looks perfect now.

http://i.imgur.com/gqXcxUH.png

**Comment by dylanaraps** [comment]
It seems like there's a whitespace issue though. I'll quickly fix it.

**Comment by dylanaraps** [comment]
I'm also fixing how it says "1 hours". Instead it'll be "1 hour" and then "2 hours"! :)

**Comment by dylanaraps** [comment]
Fixed!

Check it out!

**Comment by dylanaraps** [comment]
Can I close this issue? Is everything working now?

**Comment by jrgz** [comment]
Everything is working. Thank you for your efforts.

**Comment by dylanaraps** [comment]
No problem!
