### ISSUE TITLE
Wrong window manager display

### ISSUE THREAD

**Issue by qualious** [dylanaraps/fetch.sh#8]
Hi, me again. After the wmctrl dependency dropped, i had a little problem about my WM info.
It showed this:

![2016-01-03-122750_666x203_scrot](https://cloud.githubusercontent.com/assets/11707431/12078324/8defe836-b215-11e5-8d16-8de67498007b.png)

But i manage to get the correct wm by changing
```       
     windowmanager="${xinitrc/-session/}"
```
to
```
    windowmanager="${XDG_CURRENT_DESKTOP}"
```
I think this is an easier solution than reading .xinitrc, because some people may not have their wm info in their .xinitrc and it can show wrong results in info column. After the fix i applied, this was the output:

![2016-01-03-123052_666x204_scrot](https://cloud.githubusercontent.com/assets/11707431/12078336/f459e900-b215-11e5-9218-0bc3a8c2cb6e.png)

Hope this helps.

**Comment by dylanaraps** [comment]
Hi, thanks issue/pr!

A few things:

- What does your .xinitrc look like (If it exists)? The script checks for lines starting with "exec" that aren't commented. Your .xinitrc file should only have one line starting with "exec".

- ```"${XDG_CURRENT_DESKTOP}"```  may or may not be set. (It isn't on my pc) We'll need to check to see whether or not the variable is empty first.

I'll add a check for ```${XDG_CURRENT_DESKTOP}``` to the if statement, this should fix the issue and make everyone happy.
